# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build and upload artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Setup Java 16
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      # Setup caching to make it faster
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      # Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Build the project
      - name: Build with Gradle
        run: ./gradlew build
      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: CSF-JDk16
          path: build/libs
